export enum COOKIES_KEY {
  WEB_ACCESS_TOKEN = '_web_access_token',
  APP_ACCOUNT_INFO = '_app_account_info',
  WEB_ACCOUNT_INFO = '_web_account_info',
  ACCOUNT_INFO = '_account_info',
}

export const COOKIE_DOMAIN = process.env.NEXT_PUBLIC_COOKIE_DOMAIN || 'localhost'

export enum REACT_QUERY_KEYS {
  GET_NEWS_ARTICLE = 'get_news_article',
  GET_NEWS_ARTICLES = 'get_news_articles',
  GET_FEATURED_NEWS_ARTICLE = 'get_featured_news_article',
  GET_FEATURED_NEWS_ARTICLES = 'get_featured_news_articles',
  GET_NEWS_SOURCE = 'get_news_source',
  GET_NEWS_SOURCES = 'get_news_sources',
  GET_TOPIC = 'get_topic',
  GET_TOPICS = 'get_topics',
  GET_PODCAST = 'get_podcast',
  GET_PODCASTS = 'get_podcasts',
  GET_PODCAST_CATEGORY = 'get_podcast_category',
  GET_PODCAST_CATEGORIES = 'get_podcast_categories',
  GET_VIDEO = 'get_video',
  GET_VIDEOS = 'get_videos',
  GET_VIDEO_CHANNEL = 'get_video_channel',
  GET_VIDEO_CHANNELS = 'get_video_channels',
  GET_SUBSCRIPTION_PLAN = 'get_subscription_plan',
  GET_SUBSCRIPTION_PLANS = 'get_subscription_plans',
  GET_USER = 'get_user',
  GET_USERS = 'get_users',
  GET_USERS_SUBSCRIPTIONS = 'get_users_subscriptions',
  GET_USER_CUSTOM_VOCAB_COLLECTION = 'get_user_custom_vocab_collection',
  GET_USER_CUSTOM_VOCAB_COLLECTIONS = 'get_user_custom_vocab_collections',
  GET_NEWS_ARTICLE_HIGHLIGHT_CONTENT = 'get_news_article_highlight_content',
  GET_VOCAB_COLLECTIONS = 'get_vocab_collections',
  GET_VOCAB_COLLECTION = 'get_vocab_collection',
  GET_PARENT_VOCAB_COLLECTIONS = 'get_parent_vocab_collections',
  GET_FULL_PARENT_VOCAB_COLLECTIONS = 'get_full_parent_vocab_collections',
  GET_FULL_VOCAB_COLLECTION = 'get_full_vocab_collection',
  GET_FULL_TOPIC = 'get_full_topic',
  GET_FULL_VIDEO_CHANNEL = 'get_full_video_channel',
  GET_FULL_PODCAST_CATEGORY = 'get_full_podcast_category',
  GET_FULL_NEWS_SOURCE = 'get_full_news_source',
  GET_WORD_HIGHLIGHT_PACKS = 'get_word_highlight_packs',
  GET_HIGHLIGHT_CONTENT_NEWS_ARTICLE = 'get_highlight_content_news_article',
  GET_HIGHLIGHT_TRANSCRIPT_VIDEO = 'get_highlight_transcript_video',
  GET_HIGHLIGHT_TRANSCRIPT_PODCAST = 'get_highlight_transcript_podcast',
  GET_WORD_IN_VOCAB_COLLECTION = 'get_word_in_vocab_collection',
  GET_VIDEOS_BY_VIDEO_CHANNEL = 'get_video_by_video_channel',
  GET_CAMPAIGNS = 'get_campaigns',
  GET_CAMPAIGN = 'get_campaign',
  GET_PREMIUM_VOUCHERS = 'get_premium_voucher',
  GET_REFERRAL_CODES = 'get_referral_codes',
  GET_REFERRAL_LOG = 'get_referral_log',
  GET_REFERRAL_LOGS = 'get_referral_logs',
  GET_REFERRAL_STAT = 'get_referral_stat',
  GET_NEWS_CRAWLER_CONFIG = 'get_news_crawler_config',
  GET_NEWS_CRAWLER_CONFIGS = 'get_news_crawler_configs',
  GET_GAME_WORD = 'get_game_word',
  GET_GAME_WORDS = 'get_game_words',
  GET_FEEDBACK = 'get_feedback',
  GET_FEEDBACKS = 'get_feedbacks',
}

export enum SESSION_STORAGE_KEY {
  PAGINATION_STORAGE = 'pagination_storage',
  CURRENT_PAGE = 'current_page',
  SIDEBAR_COLLAPSE = 'sidebar_collapse',
}
